### ISSUE TITLE
Can I upload media files larger than 10Mb?

### ISSUE THREAD

**Issue by makunomark** [beachio/chisel#3]
I have a situation where I need to upload files about 150mb in size. Currently the chisel wont let me upload the file. Anyone been able to upload files larger than 10MB?

![image](https://user-images.githubusercontent.com/5811391/39447277-f23eee58-4cc9-11e8-8cf4-061e56cc71fa.png)

**Comment by Nes-si** [comment]
@makunomark 
To support larger files you should change `FILE_SIZE_MAX` value in a `ConnectConstants.js`, and set same value to `maxUploadSize` param in `config.json` of [chisel-parse-server](https://github.com/beachio/chisel-parse-server-starter). 
But you should bear in mind that Parse-server is not intended to operate with large files. Maybe we'll include an Amazon S3 adapter to use it to keep large files in near future.

**Comment by makunomark** [comment]
@Nes-si Thank you. Changing `FILE_SIZE_MAX` in `ConnectConstants.js` worked. I am using a "stand alone" version of `parse-server`, specifically a clone of [parse-server-example](https://github.com/parse-community/parse-server-example). I ended up setting up an Amazon S3 adapter. Everything works as expected. I don't mind spending a weekend including Amazon s3 adapter to `chisel-parse-server`.

**Comment by makunomark** [comment]
This solution worked, ill close this issue
