### ISSUE TITLE
License File missing

### ISSUE THREAD

**Issue by iuridiniz** [beachio/chisel#9]
A license file is missing. Also, there's no license notes in README. It's difficult to discovery which license this code use. In package.json there's a reference to MIT license. Please clarify this.

**Comment by r3trosteve** [comment]
Hi there.
Yeah currently it’s essentially MIT license but I’m considering what would be appropriate going forward. Thinking something like BSD (same as parse-server) which remains permissible and non copy-left, but does ensure that the license is protected and organisation (Beach) remains credited for ownership. Do you have any thoughts on an appropriate license? Open to suggestions

**Comment by iuridiniz** [comment]
I think that differences between the BSD (2-clause) license and the MIT license are marginal. The organisation will be referenced in the two licenses (the copyright notice). But if you are speaking about 4-clause BSD, well, there's a clause for advertising, so any  advertising material will have the organisation mentioned. 

I suggest to stay close to parse-server and choose the 3-clause BSD. But the 4-clause could be good if you need to receive credit.

**Comment by r3trosteve** [comment]
Thanks, appreciate the thoughtful response 👍

**Comment by r3trosteve** [comment]
Resolved

**Comment by iuridiniz** [comment]
I think you forget to alter package.json, This file is saying MIT license and I think I found a BSD license in your LICENSE file
